// Base de données des Associations de Keur Massar
var associationDatabase = [
    {
        id: 1,
        nom: "Association des Femmes Actives de Keur Massar",
        image: "../images/acteurs/femme asso",
        commune: "Keur Massar Nord",
        adresse: "Quartier Aïnoumady, Rue KM-15",
        telephone: "+221 77 123 45 67",
        president: "Mme. Fatoumata Diop",
        nombre: "120",
        type: "Association de femmes",
        secteur: "Développement communautaire",
        email: "afakm@email.com",
        dateCreation: "2015",
        statut: "Active"
    },
    {
        id: 2,
        nom: "Association des Jeunes pour le Développement",
        image: "../images/acteurs/femme asso",
        commune: "Keur Massar Sud",
        adresse: "Zone maraîchère, Lot 45",
        telephone: "+221 77 234 56 78",
        president: "M. Amadou Ba",
        nombre: "85",
        type: "Association de jeunes",
        secteur: "Formation et insertion",
        email: "ajdk@email.com",
        dateCreation: "2018",
        statut: "Active"
    },
    {
        id: 3,
        nom: "Association des Artisans de Malika",
        image: "../images/acteurs/femme asso",
        commune: "Malika",
        adresse: "Marché artisanal, Stand 12",
        telephone: "+221 77 345 67 89",
        president: "Mme. Awa Diouf",
        nombre: "45",
        type: "Association professionnelle",
        secteur: "Artisanat",
        email: "aam@email.com",
        dateCreation: "2012",
        statut: "Active"
    },
    {
        id: 4,
        nom: "Association des Commerçants de Yeumbeul",
        image: "../images/acteurs/femme asso",
        commune: "Yeumbeul Nord",
        adresse: "Marché Central, N°23",
        telephone: "+221 77 456 78 90",
        president: "M. Ousmane Sow",
        nombre: "95",
        type: "Association professionnelle",
        secteur: "Commerce",
        email: "acy@email.com",
        dateCreation: "2010",
        statut: "Active"
    },
    {
        id: 5,
        nom: "Association des Couturières Modernes",
        image: "../images/acteurs/femme asso",
        commune: "Keur Massar Sud",
        adresse: "Cité des Artisans, N°45",
        telephone: "+221 77 567 89 01",
        president: "Mme. Khady Dieng",
        nombre: "35",
        type: "Association de femmes",
        secteur: "Couture et mode",
        email: "acm@email.com",
        dateCreation: "2016",
        statut: "Active"
    },
    {
        id: 6,
        nom: "Association des Femmes An Nour",
        image: "../images/acteurs/femme asso",
        commune: "Keur Massar Nord",
        adresse: "QRT Layenne Villa N126",
        telephone: "+221 77 574 22 85",
        president: "Mme. Kenebougoul Haby Sall",
        nombre: "80",
        type: "Association de femmes",
        secteur: "Commerce et développement",
        email: "afan@email.com",
        dateCreation: "2014",
        statut: "Active"
    },
    {
        id: 7,
        nom: "Association And Ci Deug Suxali Yeumbeul",
        image: "../images/acteurs/femme asso",
        commune: "Yeumbeul Sud",
        adresse: "Yeumbeul Sud QRT Malick Diop Villa N173",
        telephone: "+221 78 311 22 09",
        president: "Mme. Amy Beye",
        nombre: "150",
        type: "Association communautaire",
        secteur: "Développement local",
        email: "acdsy@email.com",
        dateCreation: "2011",
        statut: "Active"
    },
    {
        id: 8,
        nom: "Association Kadiamor Keur Massar",
        image: "../images/acteurs/femme asso",
        commune: "Keur Massar Nord",
        adresse: "Yeumbeul Nord QRT Sant Yalla",
        telephone: "+221 77 711 85 34",
        president: "Mme. Diarra Sane",
        nombre: "110",
        type: "Association de femmes",
        secteur: "Transformation et commerce",
        email: "akkm@email.com",
        dateCreation: "2013",
        statut: "Active"
    },
    {
        id: 9,
        nom: "Association des Agriculteurs de Keur Massar",
        image: "../images/acteurs/femme asso",
        commune: "Keur Massar Sud",
        adresse: "Zone agricole, Parcelle 78",
        telephone: "+221 77 678 90 12",
        president: "M. Mamadou Diallo",
        nombre: "65",
        type: "Association professionnelle",
        secteur: "Agriculture",
        email: "aakm@email.com",
        dateCreation: "2017",
        statut: "Active"
    },
    {
        id: 10,
        nom: "Association des Femmes Entrepreneures",
        image: "../images/acteurs/femme asso",
        commune: "Malika",
        adresse: "Centre d'Affaires, N°15",
        telephone: "+221 77 789 01 23",
        president: "Mme. Mariama Fall",
        nombre: "55",
        type: "Association de femmes",
        secteur: "Entrepreneuriat",
        email: "afe@email.com",
        dateCreation: "2019",
        statut: "Active"
    },
    {
        id: 11,
        nom: "Association des Jeunes Artisans",
        image: "../images/acteurs/femme asso",
        commune: "Yeumbeul Nord",
        adresse: "Atelier des Jeunes, N°8",
        telephone: "+221 77 890 12 34",
        president: "M. Ibrahima Ndiaye",
        nombre: "40",
        type: "Association de jeunes",
        secteur: "Artisanat",
        email: "aja@email.com",
        dateCreation: "2020",
        statut: "Active"
    },
    {
        id: 12,
        nom: "Association des Femmes pour l'Éducation",
        image: "../images/acteurs/femme asso",
        commune: "Keur Massar Nord",
        adresse: "Centre Éducatif, Rue de l'École",
        telephone: "+221 77 901 23 45",
        president: "Mme. Aminata Mbaye",
        nombre: "75",
        type: "Association de femmes",
        secteur: "Éducation",
        email: "afe@email.com",
        dateCreation: "2016",
        statut: "Active"
    },
    {
        id: 13,
        nom: "Association des Commerçants de Malika",
        image: "../images/acteurs/femme asso",
        commune: "Malika",
        adresse: "Marché de Malika, Stand 25",
        telephone: "+221 77 012 34 56",
        president: "M. Abdou Sall",
        nombre: "90",
        type: "Association professionnelle",
        secteur: "Commerce",
        email: "acm@email.com",
        dateCreation: "2012",
        statut: "Active"
    },
    {
        id: 14,
        nom: "Association des Femmes pour la Santé",
        image: "../images/acteurs/femme asso",
        commune: "Yeumbeul Sud",
        adresse: "Centre de Santé, N°12",
        telephone: "+221 77 123 45 67",
        president: "Mme. Fatou Ndiaye",
        nombre: "60",
        type: "Association de femmes",
        secteur: "Santé communautaire",
        email: "afs@email.com",
        dateCreation: "2018",
        statut: "Active"
    },
    {
        id: 15,
        nom: "Association des Jeunes pour l'Environnement",
        image: "../images/acteurs/femme asso",
        commune: "Keur Massar Sud",
        adresse: "Parc Écologique, N°3",
        telephone: "+221 77 234 56 78",
        president: "M. Modou Diop",
        nombre: "50",
        type: "Association de jeunes",
        secteur: "Environnement",
        email: "aje@email.com",
        dateCreation: "2021",
        statut: "Active"
    },
    {
        id: 16,
        nom: "Association des Femmes pour la Culture",
        image: "../images/acteurs/femme asso",
        commune: "Keur Massar Nord",
        adresse: "Centre Culturel, N°7",
        telephone: "+221 77 345 67 89",
        president: "Mme. Aissatou Diallo",
        nombre: "45",
        type: "Association de femmes",
        secteur: "Culture et arts",
        email: "afc@email.com",
        dateCreation: "2017",
        statut: "Active"
    },
    {
        id: 17,
        nom: "Association des Artisans du Cuir",
        image: "../images/acteurs/femme asso",
        commune: "Yeumbeul Nord",
        adresse: "Zone Artisanale, N°18",
        telephone: "+221 77 456 78 90",
        president: "M. Moussa Ba",
        nombre: "30",
        type: "Association professionnelle",
        secteur: "Artisanat du cuir",
        email: "aac@email.com",
        dateCreation: "2015",
        statut: "Active"
    },
    {
        id: 18,
        nom: "Association des Femmes pour le Microcrédit",
        image: "../images/acteurs/femme asso",
        commune: "Malika",
        adresse: "Centre Financier, N°22",
        telephone: "+221 77 567 89 01",
        president: "Mme. Khady Fall",
        nombre: "100",
        type: "Association de femmes",
        secteur: "Microfinance",
        email: "afm@email.com",
        dateCreation: "2014",
        statut: "Active"
    },
    {
        id: 19,
        nom: "Association des Jeunes pour le Sport",
        image: "../images/acteurs/femme asso",
        commune: "Keur Massar Sud",
        adresse: "Terrain de Sport, N°5",
        telephone: "+221 77 678 90 12",
        president: "M. Pape Diouf",
        nombre: "80",
        type: "Association de jeunes",
        secteur: "Sport et loisirs",
        email: "ajs@email.com",
        dateCreation: "2019",
        statut: "Active"
    },
    {
        id: 20,
        nom: "Association des Femmes pour la Paix",
        image: "../images/acteurs/femme asso",
        commune: "Yeumbeul Sud",
        adresse: "Centre de Paix, N°9",
        telephone: "+221 77 789 01 23",
        president: "Mme. Mariama Sall",
        nombre: "70",
        type: "Association de femmes",
        secteur: "Paix et cohésion sociale",
        email: "afp@email.com",
        dateCreation: "2016",
        statut: "Active"
    },
    {
        id: 21,
        nom: "Association des Commerçants de Jaxaay",
        image: "../images/acteurs/femme asso",
        commune: "Jaxaay-Parcelles",
        adresse: "Marché de Jaxaay, Stand 30",
        telephone: "+221 77 890 12 34",
        president: "M. Ousmane Diop",
        nombre: "85",
        type: "Association professionnelle",
        secteur: "Commerce",
        email: "acj@email.com",
        dateCreation: "2013",
        statut: "Active"
    },
    {
        id: 22,
        nom: "Association des Femmes pour l'Innovation",
        image: "../images/acteurs/femme asso",
        commune: "Keur Massar Nord",
        adresse: "Centre d'Innovation, N°11",
        telephone: "+221 77 901 23 45",
        president: "Mme. Aminata Ba",
        nombre: "40",
        type: "Association de femmes",
        secteur: "Innovation technologique",
        email: "afi@email.com",
        dateCreation: "2020",
        statut: "Active"
    },
    {
        id: 23,
        nom: "Association des Artisans du Bois",
        image: "../images/acteurs/femme asso",
        commune: "Malika",
        adresse: "Atelier du Bois, N°14",
        telephone: "+221 77 012 34 56",
        president: "M. Ibrahima Sall",
        nombre: "35",
        type: "Association professionnelle",
        secteur: "Menuiserie",
        email: "aab@email.com",
        dateCreation: "2014",
        statut: "Active"
    },
    {
        id: 24,
        nom: "Association des Femmes pour le Tourisme",
        image: "../images/acteurs/femme asso",
        commune: "Yeumbeul Nord",
        adresse: "Office de Tourisme, N°6",
        telephone: "+221 77 123 45 67",
        president: "Mme. Fatou Dieng",
        nombre: "55",
        type: "Association de femmes",
        secteur: "Tourisme",
        email: "aft@email.com",
        dateCreation: "2018",
        statut: "Active"
    },
    {
        id: 25,
        nom: "Association des Jeunes pour la Formation",
        image: "../images/acteurs/femme asso",
        commune: "Keur Massar Sud",
        adresse: "Centre de Formation, N°16",
        telephone: "+221 77 234 56 78",
        president: "M. Modou Fall",
        nombre: "95",
        type: "Association de jeunes",
        secteur: "Formation professionnelle",
        email: "ajf@email.com",
        dateCreation: "2017",
        statut: "Active"
    }
]; 